server:
    port: 8090
logging:
  config: classpath:logback-spring.xml
  path: /applogs
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/framework
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: dev
