server:
    port: 8090
logging:
  config: classpath:logback-spring.xml
  path: /applogs
  level:
    root: info
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver